/**
 * POST-PROCESSING FOR THE ALLURE REPORT
 * Checks all of the json files generated by allure and
 * appends a warning icon to the suite name and test name for easy
 * location of any warnings that tests may have
 */

import path from 'path';
import { REPORTS_PATH } from '@configs/reports/reporters.config.ts';
import { Logger } from '@utils/logger.ts';
import { FSHelpers } from '@utils/fs/fsHelpers.ts';

const RESULTS_DIR: string = path.join(REPORTS_PATH, 'allure-results');
// Indicators (substrings) in the log that would trigger the warning icon to be added to test name
const INDICATORS: string[] = ['⚠️', '⛔'];

/**
 * Read the attachment
 * @param source
 * @returns
 */
function readAttachment(source: string): string | null {
    const filePath = path.join(RESULTS_DIR, source);
    return FSHelpers.readFileSafe(filePath);
}

/**
 * Check if the provided text includes any indicator of a warning
 * (warning indicators are all listed in INDICATORS array)
 * @param text
 * @returns
 */
function textHasWarning(text: string): boolean {
    return INDICATORS.some((substr: string) => text.includes(substr));
}

/**
 * Alters the given text and prepends it with a warning icon
 * if the icon is not already present in it
 * @param text
 * @returns
 */
function appendWarning(text: string): string {
    if (!text.includes('⚠️')) return `⚠️ ${text}`;
    return text;
}

/**
 * Run the post-processing actions on the generated allure reports
 */
export default function processAllureResults() {
    const files = FSHelpers.readDirSafe(RESULTS_DIR);
    const resultFiles = files.filter((f) => f.endsWith('-result.json'));

    const results: { suite: string; test: string }[] = [];

    for (const file of resultFiles) {
        const fullPath = path.join(RESULTS_DIR, file);
        const json = JSON.parse(FSHelpers.readFileSafe(fullPath));

        if (!json.attachments) continue;

        let hasWarning = false;

        // Scan attachments for warning indicators and compile list of tests + suites that includes them
        for (const att of json.attachments) {
            const log = readAttachment(att.source);
            if (!log) continue;

            if (textHasWarning(log)) {
                hasWarning = true;
                results.push({
                    suite: json.fullName?.split(/[:→]/)?.[0] ?? 'Unknown Suite',
                    test: json.name,
                });
                break; // No need to scan more attachments for this test
            }
        }

        if (hasWarning) {
            // Append ⚠️ to test name if a warning was found
            json.name = appendWarning(json.name);

            // labels that should also have a warning attached in addition to the test names
            // the Suites page of the report and path traversal uses labels for display names
            // so we need to append those for easy indication of which suites have warnings
            for (let i = 0; i < json.labels.length; i++) {
                if (['parentSuite', 'suite', 'subSuite'].includes(json.labels[i].name)) {
                    json.labels[i].value = appendWarning(json.labels[i].value);
                }
            }

            // Overwrite the JSON file
            FSHelpers.writeTextFileSafe(fullPath, json, 'json');
        }
    }

    // log a debug message
    const msg: string = results.length
        ? `${results.length} warning/error logs found in the tests. 
                            Suite and test names have been updated to reflect which ones have the warnings.`
        : `No warning logs found in the reports.`;

    Logger.debug(msg);
}
